### ISSUE TITLE
Lage en metode på å hente ut bruker, som et objekt. Dette kan gjøres i Mainactivity. Trenger muligens å vite om brukeren flere steder.

### ISSUE THREAD

**Issue by sjoholt** [sjoholt/Prosjektoppgave-Android#13]

**Comment by DemyxIX** [comment]
loadUsers er klar til å hente ut bruker, men må ha autorisering (passord/loginn) delen får vi kan ta den i bruk

**Comment by sjoholt** [comment]
Tror dette kan gjøres rimelig enkelt med løsningen på authentisering Mikael viste oss. Serveren vet hvem som er logget inn, og da kan vi bruke en SecurityContext for å få tak i brukeren.

SecurityContext ctx;
ctx.getUserPrincipal().getName();
